apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: arender-pool-1
  namespace: int-arender-dev
  name: arender-pool-1-lb-tester-client
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: arender-pool-1
    role: lb-tester-client
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arender-pool-1
        role: lb-tester-client
    spec:
      containers:
        - env:
            - name: HOST_NAME
              value: "http://arender-pool-1-lb-tester-server:20000"
            - name: NUMBER_REQUESTS
              value: '2000'
            - name: USE_LB_HEADERS
              value: 'true'
            - name: RECYCLE_REST_TEMPLATE
              value: 'true'
            - name: USE_EXCHANGE
              value: 'true'
            - name: DISABLE_DNS_CACHING
              value: 'true'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: >-
            chocobosan/lb-tester-client:1.0.3
          imagePullPolicy: Always
          name: lb-tester-client
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: arender-pool-1-service-account
      serviceAccountName: arender-pool-1-service-account
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange